#!/usr/bin/env python3
"""
Wiki Q&A Script — задаёт вопросы по wiki и сохраняет ответы в outputs/

Usage:
    python3 wiki_qa.py --ask "question"
    python3 wiki_qa.py --ask "question" --save
    python3 wiki_qa.py --recent
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

WIKI_DIR = Path(__file__).parent
OUTPUTS_DIR = WIKI_DIR / "outputs"
WIKI_DIR_PATH = str(WIKI_DIR / "wiki")

DEFAULT_MODEL = "qwen2.5:3b"
VISION_MODEL = "llama3.2-vision"


def get_ollama_model(prompt: str, has_images: bool = False) -> str:
    """Выбрать модель"""
    if has_images or "image" in prompt.lower() or "картинк" in prompt.lower():
        return VISION_MODEL
    return DEFAULT_MODEL


def build_context() -> str:
    """Собрать контекст из wiki для промпта"""
    wiki_files = list(Path(WIKI_DIR_PATH).glob("*.md"))

    context_parts = ["# Wiki Content\n"]

    for f in sorted(wiki_files)[:15]:  # Ограничиваем — 32K context
        try:
            content = f.read_text(encoding="utf-8")[:3000]  # Первые 3K
            context_parts.append(f"## {f.name}\n{content}\n")
        except:
            pass

    return "\n\n".join(context_parts)


def ask_ollama(question: str, model: str = None) -> str:
    """Задать вопрос Ollama"""
    if model is None:
        model = get_ollama_model(question)

    context = build_context()

    prompt = f"""Ты — эксперт по AI Testing и QA. Используя контекст ниже, ответь на вопрос.

## Контекст из Wiki
{context}

## Вопрос
{question}

## Ответ (markdown с цитатами)"""

    print(f"🤖 Using model: {model}")

    result = subprocess.run(
        ["ollama", "run", model, prompt],
        capture_output=True,
        text=True,
        timeout=300
    )

    if result.returncode != 0:
        print(f"❌ Error: {result.stderr}", file=sys.stderr)
        return ""

    return result.stdout.strip()


def save_to_outputs(question: str, answer: str, tags: list = None):
    """Сохранить ответ в outputs/"""
    OUTPUTS_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    filename = f"qa_{timestamp}.md"
    filepath = OUTPUTS_DIR / filename

    frontmatter = f"""---
question: "{question}"
date: "{datetime.now().isoformat()}"
tags: {tags or ['qa']}
---

"""

    content = f"""{frontmatter}

# Q: {question}

## A

{answer}

---

*Generated by wiki_qa.py*
"""

    filepath.write_text(content, encoding="utf-8")
    print(f"💾 Saved to: {filepath.name}")
    return filepath


def list_recent_outputs(n: int = 5):
    """Показать последние outputs"""
    if not OUTPUTS_DIR.exists():
        print("📭 No outputs yet")
        return

    files = sorted(OUTPUTS_DIR.glob("qa_*.md"), reverse=True)[:n]

    if not files:
        print("📭 No outputs yet")
        return

    print(f"📋 Last {len(files)} outputs:\n")
    for f in files:
        date = datetime.fromisoformat(f.read_yaml()["date"][:10]) if False else "N/A"
        print(f"  • {f.name}")


def main():
    parser = argparse.ArgumentParser(description="Wiki Q&A Script")
    parser.add_argument("--ask", type=str, help="Вопрос по wiki")
    parser.add_argument("--save", action="store_true", help="Сохранить ответ в outputs/")
    parser.add_argument("--recent", action="store_true", help="Показать последние ответы")
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL, help="Ollama модель")

    args = parser.parse_args()

    if args.recent:
        list_recent_outputs()
        return

    if args.ask:
        print(f"❓ Question: {args.ask}\n")
        answer = ask_ollama(args.ask, args.model)

        if answer:
            print(f"## Answer\n\n{answer}\n")

            if args.save:
                save_to_outputs(args.ask, answer)
        else:
            print("❌ No answer received")
            sys.exit(1)
        return

    parser.print_help()


if __name__ == "__main__":
    main()