#!/usr/bin/env python3
"""
Wiki Q&A Script — задаёт вопросы по wiki и сохраняет ответы в outputs/

Usage:
    python3 wiki_qa.py --ask "question"
    python3 wiki_qa.py --ask "question" --save
    python3 wiki_qa.py --recent
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

WIKI_DIR = Path(__file__).parent
OUTPUTS_DIR = WIKI_DIR / "outputs"
WIKI_DIR_PATH = str(WIKI_DIR / "wiki")

DEFAULT_MODEL = "llama3.2:3b"
VISION_MODEL = "llama3.2-vision"


def get_ollama_model(prompt: str, has_images: bool = False) -> str:
    """Выбрать модель"""
    if has_images or "image" in prompt.lower() or "картинк" in prompt.lower():
        return VISION_MODEL
    return DEFAULT_MODEL


def find_relevant_files(query: str, top_n: int = 3) -> list:
    """Найти релевантные файлы по ключевым словам"""
    keywords = query.lower().split()
    wiki_files = list(Path(WIKI_DIR_PATH).glob("*.md"))

    scores = {}
    for f in wiki_files:
        try:
            content = f.read_text(encoding="utf-8").lower()
            score = sum(1 for kw in keywords if kw in content)
            if score > 0:
                scores[f] = score
        except:
            pass

    sorted_files = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return [f for f, _ in sorted_files[:top_n]]


def build_context(query: str = "") -> str:
    """Собрать контекст из wiki для промпта (релевантность по ключевым словам)"""
    wiki_files = find_relevant_files(query) if query else list(Path(WIKI_DIR_PATH).glob("*.md"))[:3]

    context_parts = ["# Wiki Content (short)\n"]

    # По 1K символов на файл = ~3K total
    for f in wiki_files:
        try:
            content = f.read_text(encoding="utf-8")[:1000]
            context_parts.append(f"## {f.name}\n{content}\n")
        except:
            pass

    return "\n\n".join(context_parts)


def ask_ollama(question: str, model: str = None) -> str:
    """Задать вопрос Ollama через API с использованием wiki контекста"""
    import requests
    import json

    if model is None:
        model = get_ollama_model(question)

    context = build_context(question)

    system_prompt = """Ты — эксперт по AI Testing и QA.
Отвечай на основе предоставленного контекста из wiki.
Если информации нет в контексте — честно скажи "нет данных в wiki"."""

    full_prompt = f"""## Контекст из Wiki
{context}

## Вопрос
{question}

## Инструкция
Ответь кратко (3-5 предложений) используя Wiki контекст."""

    print(f"🤖 Using model: {model} (API)")

    try:
        response = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": model,
                "prompt": full_prompt,
                "system": system_prompt,
                "stream": False,
                "options": {
                    "num_ctx": 32768,
                    "temperature": 0.3
                }
            },
            timeout=300
        )

        if response.status_code != 200:
            print(f"❌ API Error: {response.text}", file=sys.stderr)
            return ""

        result = response.json()
        return result.get("response", "").strip()

    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        return ""


def save_to_outputs(question: str, answer: str, tags: list = None):
    """Сохранить ответ в outputs/"""
    OUTPUTS_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    filename = f"qa_{timestamp}.md"
    filepath = OUTPUTS_DIR / filename

    frontmatter = f"""---
question: "{question}"
date: "{datetime.now().isoformat()}"
tags: {tags or ['qa']}
---

"""

    content = f"""{frontmatter}

# Q: {question}

## A

{answer}

---

*Generated by wiki_qa.py*
"""

    filepath.write_text(content, encoding="utf-8")
    print(f"💾 Saved to: {filepath.name}")
    return filepath


def list_recent_outputs(n: int = 5):
    """Показать последние outputs"""
    if not OUTPUTS_DIR.exists():
        print("📭 No outputs yet")
        return

    files = sorted(OUTPUTS_DIR.glob("qa_*.md"), reverse=True)[:n]

    if not files:
        print("📭 No outputs yet")
        return

    print(f"📋 Last {len(files)} outputs:\n")
    for f in files:
        try:
            text = f.read_text(encoding="utf-8")
            date_line = [l for l in text.split("\n") if l.startswith("date:")][0]
            date = date_line.split('"')[1][:10] if '"' in date_line else "N/A"
        except:
            date = "N/A"
        print(f"  • {f.name}  ({date})")


def main():
    parser = argparse.ArgumentParser(description="Wiki Q&A Script")
    parser.add_argument("--ask", type=str, help="Вопрос по wiki")
    parser.add_argument("--save", action="store_true", help="Сохранить ответ в outputs/")
    parser.add_argument("--recent", action="store_true", help="Показать последние ответы")
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL, help="Ollama модель")

    args = parser.parse_args()

    if args.recent:
        list_recent_outputs()
        return

    if args.ask:
        print(f"❓ Question: {args.ask}\n")
        answer = ask_ollama(args.ask, args.model)

        if answer:
            print(f"## Answer\n\n{answer}\n")

            if args.save:
                save_to_outputs(args.ask, answer)
        else:
            print("❌ No answer received")
            sys.exit(1)
        return

    parser.print_help()


if __name__ == "__main__":
    main()