#!/usr/bin/env python3
"""
wiki_lint.py — Deterministic health check for the AI QA Wiki (replaces manual Sunday ritual).

Checks (all deterministic, no LLM context):
  1. Broken links in wiki/ (wiki/*.md, raw/*.md, plus cross-repo ../../Positions-CV-CL|Articles links
     and github.com/victor-2026/positions-cv-cl-private/blob/main links, resolved to local paths)
  2. Orphan pages (wiki/*.md with no inbound links from any other wiki page)
  3. Stub pages (<200 chars of content, excluding frontmatter/footers)
4. Raw files without a wiki counterpart (uses wiki_llm.missing_raw_files)
5. Duplicate titles (near-identical stems that may be dupes)
6. Quotes verity (W5, 2026-09-23): quoted strings 40+ chars need a source URL/Source
   marker within +-3 lines; if a same-stem raw file exists the quote must occur
   in it verbatim. P2 severity.

Usage:
    python3 wiki_lint.py                      — run ALL checks, print summary
    python3 wiki_lint.py --summary            — only counts, no per-page detail
    python3 wiki_lint.py --auto               — non-interactive, exit code 0 if no P1 broken links
    python3 wiki_lint.py --report-only        — just notes, don't fix
    python3 wiki_lint.py --fix-orphans        — create See-also cross-links from topically-related pages
    python3 wiki_lint.py --json               — machine-readable output

Exit codes:
    0 clean / nothing to fix
    1 P1 issues found (broken links, incl. cross-repo)
    2 P2 issues found (orphans / stubs / missing)
    3 P3 only (informational)

Output: outputs/lint-report-YYYY-MM-DD.md (always written).
"""

import re
import sys
import json
import datetime
from pathlib import Path
from urllib.parse import unquote

PROJECT_DIR = Path(__file__).parent
WIKI_DIR = PROJECT_DIR / "wiki"
RAW_DIR = PROJECT_DIR / "raw"
OUTPUTS_DIR = PROJECT_DIR / "outputs"
REPORT_DIR = OUTPUTS_DIR

INTERNAL_LINK_RE = re.compile(r"\[[^\]]*\]\(((?:wiki|raw)/[^)#\s]+)\.md(?:#[\w-]+)?\)")
SKIP_FILES = {"log.md", "README.md", "index.md"}

# Cross-repo links: ../../Positions-CV-CL|Articles relative paths and absolute
# github URLs of the private repo, resolved to local checkouts. Bases missing
# on disk (other machines) => check skipped, never a false positive.
CROSS_REPO_RE = re.compile(r"\[[^\]]*\]\((\.\./\.\./(Positions-CV-CL|Articles)/(?:[^)\s]|\([^)]*\))+?\.md)(?:#[\w-]+)?\)")
GITHUB_CROSS_RE = re.compile(r"\[[^\]]*\]\(https://github\.com/victor-2026/positions-cv-cl-private/blob/main/([^)\s]+?\.md)(?:#[\w-]+)?\)")
CROSS_REPO_BASES = {
    "Positions-CV-CL": Path("/Users/victor/Private/Positions-CV-CL"),
    "Articles": Path("/Users/victor/Projects/Articles"),
}


def read_page(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""


def strip_boilerplate(content: str) -> str:
    """Remove frontmatter, backlinks block, and generated-footer to measure real content size."""
    lines = content.split("\n")
    out = []
    in_fm = False
    if lines and lines[0].strip() == "---":
        in_fm = True
    for ln in lines:
        if in_fm:
            if ln.strip() == "---":
                in_fm = False
            continue
        if "<!-- backlinks-start -->" in ln or "<!-- backlinks-end -->" in ln:
            continue
        if ln.startswith("*Generated by"):
            continue
        out.append(ln)
    return "\n".join(out)


def internal_links(content: str) -> list:
    return [m.group(1) + ".md" for m in INTERNAL_LINK_RE.finditer(content)]


def cross_repo_links(content: str) -> list:
    """Returns [(raw_link, local_target_Path)]. Unresolvable bases are skipped."""
    out = []
    for m in CROSS_REPO_RE.finditer(content):
        raw, vault = m.group(1), m.group(2)
        base = CROSS_REPO_BASES.get(vault)
        if base is None or not base.is_dir():
            continue
        rel = "/".join(raw.split("/")[3:])
        out.append((raw, base / unquote(rel)))
    base = CROSS_REPO_BASES["Positions-CV-CL"]
    if base.is_dir():
        for m in GITHUB_CROSS_RE.finditer(content):
            raw = m.group(1)
            out.append(("github:" + raw, base / unquote(raw)))
    return out


def all_wiki_pages() -> list:
    return sorted(p for p in WIKI_DIR.glob("*.md") if p.name not in SKIP_FILES)


def check_broken_links() -> (list, int):
    """Returns (broken, total). wiki/raw targets checked by name; cross-repo
    targets resolved to local paths (skipped when base checkout is absent)."""
    existing_wiki = {p.name for p in WIKI_DIR.glob("*.md")}
    existing_raw = {p.name for p in RAW_DIR.iterdir() if p.is_file()}
    broken = []
    total = 0
    for p in all_wiki_pages():
        content = read_page(p)
        for link in internal_links(content):
            total += 1
            if link.startswith("wiki/"):
                target = link[len("wiki/"):]
                if target not in existing_wiki:
                    broken.append((p.name, link, "wiki target missing"))
            elif link.startswith("raw/"):
                target = link[len("raw/"):]
                if target not in existing_raw:
                    broken.append((p.name, link, "raw target missing"))
        for raw, target in cross_repo_links(content):
            total += 1
            if not target.is_file():
                broken.append((p.name, raw, "cross-repo target missing"))
    return broken, total


def inbound_links() -> dict:
    """Map every wiki page stem → set of stems that link to it."""
    incoming = {}
    pages = all_wiki_pages()
    for p in pages:
        content = read_page(p)
        for link in internal_links(content):
            if link.startswith("wiki/"):
                target = link[len("wiki/"):-3]
                incoming.setdefault(target, set()).add(p.stem)
    return incoming


def check_orphans() -> list:
    pages = all_wiki_pages()
    incoming = inbound_links()
    orphans = []
    for p in pages:
        if p.stem not in incoming:
            orphans.append(p.name)
    return orphans


def check_stubs(min_chars: int = 200) -> list:
    stubs = []
    for p in all_wiki_pages():
        size = len(strip_boilerplate(read_page(p)).strip())
        if size < min_chars:
            stubs.append((p.name, size))
    return stubs


def check_missing_raw() -> list:
    sys.path.insert(0, str(PROJECT_DIR))
    try:
        from wiki_llm import missing_raw_files
        return [f.name for f in missing_raw_files()]
    except Exception:
        return ["(wiki_llm import failed)"]


def check_dupes() -> list:
    """Near-identical stems that likely duplicate a topic."""
    pages = all_wiki_pages()
    stems = [p.stem for p in pages]
    dupes = []
    seen = {}
    for i, s in enumerate(stems):
        norm = re.sub(r"[^a-z0-9]", "", s.lower())
        if norm in seen:
            dupes.append((seen[norm], s))
        else:
            seen[norm] = s
    return dupes


QUOTE_RE = re.compile(r'[«“"]([^«“”"]{40,}?)[»”"]')
URL_RE = re.compile(r"https?://\S+")
FENCED_CODE_RE = re.compile(r"```.*?```", re.S)
INLINE_CODE_RE = re.compile(r"`[^`\n]+`")


def strip_code(content: str) -> str:
    """Remove fenced + inline code so literals (CSV values, commands) aren't read as quotes."""
    content = FENCED_CODE_RE.sub("", content)
    return INLINE_CODE_RE.sub("", content)


def norm(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip().lower()


def check_quotes_verity() -> list:
    """Two-tier quote check (W5 proposal, 2026-09-23 — catches fabricated quotes).
    Tier 1: quoted string (40+ chars) must have a source URL or 'Source' marker
            within +-3 lines. Tier 2: if a same-stem raw file exists, the quote's
            first 80 chars (normalized) must occur in it verbatim.
    Returns [(page, quote_preview, kind)] where kind is 'no-source' or 'not-in-raw'."""
    issues = []
    raw_cache = {}
    for p in all_wiki_pages():
        content = strip_code(strip_boilerplate(read_page(p)))
        page_refs_ok = bool(
            re.search(r"(?im)^#{1,3}\s+.*(reference|source)", content)
            and URL_RE.search(content)
        )
        lines = content.split("\n")
        seen = set()
        for i, ln in enumerate(lines):
            if ln.lstrip().startswith("!"):
                continue  # image markup, not prose quotes
            for m in QUOTE_RE.finditer(ln):
                q = norm(m.group(1))
                if not q or q in seen:
                    continue
                if re.search(r"\.md\b|/", q):
                    continue  # filenames/paths, not quotes
                seen.add(q)
                window = "\n".join(lines[max(0, i - 3):i + 4])
                has_src = bool(
                    URL_RE.search(window)
                    or re.search(r"(?i)\bsource\b", window)
                    or page_refs_ok
                )
                attr_nearby = bool(
                    re.search(r"[—–-]\s*[A-ZА-ЯЁ][\w.,() ]{1,50}", window)
                    or re.search(r"(?i)\bsource\b|https?://", window)
                )
                if not has_src:
                    issues.append((p.name, q[:80], "no-source"))
                    continue
                stem = p.stem
                if stem not in raw_cache:
                    raw_cache[stem] = None
                    for cand in (RAW_DIR / (stem + ".md"), RAW_DIR / (stem + ".txt")):
                        if cand.exists():
                            raw_cache[stem] = norm(read_page(cand))
                            break
                raw_text = raw_cache[stem]
                if (
                    raw_text is not None
                    and attr_nearby
                    and i >= 12
                    and q[:80] not in raw_text
                ):
                    issues.append((p.name, q[:80], "not-in-raw"))
    return issues


def run_all(verbose: bool = True) -> dict:
    broken, total_links = check_broken_links()
    orphans = check_orphans()
    stubs = check_stubs()
    missing = check_missing_raw()
    dupes = check_dupes()
    quotes = check_quotes_verity()

    report = {
        "timestamp": datetime.datetime.now().isoformat(),
        "wiki_pages": len(all_wiki_pages()),
        "internal_links_ok": total_links - len(broken),
        "broken_links": broken,
        "orphans": orphans,
        "stubs": stubs,
        "missing_raw": missing,
        "dupes": dupes,
        "quotes_verity": quotes,
    }
    if verbose:
        print(f"\n🔍 Wiki lint ({report['wiki_pages']} pages)")
        print(f"  ✅ Internal links OK: {report['internal_links_ok']}")
        print(f"  ❌ Broken links: {len(broken)}")
        for p, l, why in broken:
            print(f"      {p} → {l} ({why})")
        print(f"  🕳️  Orphans: {len(orphans)}")
        for o in orphans[:40]:
            print(f"      {o}")
        if len(orphans) > 40:
            print(f"      … and {len(orphans)-40} more")
        print(f"  📄 Stubs (<200 chars): {len(stubs)}")
        for s, n in stubs[:40]:
            print(f"      {s} ({n} chars)")
        if len(stubs) > 40:
            print(f"      … and {len(stubs)-40} more")
        print(f"  ⚠️  Raw without wiki: {len(missing)}")
        for m in missing[:30]:
            print(f"      {m}")
        if len(missing) > 30:
            print(f"      … and {len(missing)-30} more")
        print(f"  🔁 Duplicate-ish stems: {len(dupes)}")
        for a, b in dupes[:30]:
            print(f"      {a} ↔ {b}")
        print(f"  💬 Quotes verity issues: {len(quotes)}")
        for p, q, kind in quotes[:30]:
            print(f"      {p} [{kind}]: {q}…")
        if len(quotes) > 30:
            print(f"      … and {len(quotes)-30} more")
    return report


def parse_history() -> list:
    """Parse previous lint-report-*.md files (excluding today's) into per-date metric rows."""
    today = datetime.date.today().isoformat()
    rows = []
    pats = {
        "pages": re.compile(r"^- Wiki pages: (\d+)$", re.M),
        "links": re.compile(r"^- Internal links OK: (\d+)$", re.M),
        "broken": re.compile(r"^- Broken links: (\d+)$", re.M),
        "orphans": re.compile(r"^- Orphans: (\d+)$", re.M),
        "stubs": re.compile(r"^- Stubs \(<200 chars\): (\d+)$", re.M),
        "missing": re.compile(r"^- Raw without wiki: (\d+)$", re.M),
        "dupes": re.compile(r"^- Duplicate-ish stems: (\d+)$", re.M),
        "quotes": re.compile(r"^- Quotes verity issues: (\d+)$", re.M),
    }
    for f in sorted(REPORT_DIR.glob("lint-report-*.md")):
        date = f.stem.replace("lint-report-", "")
        if date >= today:
            continue
        content = f.read_text(encoding="utf-8", errors="ignore")
        row = {"date": date}
        ok = True
        for key, pat in pats.items():
            m = pat.search(content)
            if not m:
                ok = False
                break
            row[key] = int(m.group(1))
        if ok:
            rows.append(row)
    return rows


def trend_lines(history: list) -> list:
    """Render history as a compact markdown table (oldest → newest), plus deltas."""
    header = "| Run | Pages | Links OK | Broken | Orphans | Stubs | Missing raw | Dupes | delta orphans | delta missing |"
    sep = "|-----|-------|----------|--------|---------|-------|-------------|-------|----------------|---------------|"
    out = [header, sep]
    prev = None
    for row in history:
        d_or = f"{row['orphans'] - prev['orphans']:+d}" if prev else "—"
        d_mi = f"{row['missing'] - prev['missing']:+d}" if prev else "—"
        out.append(
            f"| {row['date']} | {row['pages']} | {row['links']} | {row['broken']} "
            f"| {row['orphans']} | {row['stubs']} | {row['missing']} | {row['dupes']} "
            f"| {d_or} | {d_mi} |"
        )
        prev = row
    return out


def write_report(report: dict) -> Path:
    OUTPUTS_DIR.mkdir(exist_ok=True)
    today = datetime.date.today().isoformat()
    dst = REPORT_DIR / f"lint-report-{today}.md"
    lines = [f"# Wiki Lint Report — {today}", ""]
    lines.append(f"- Timestamp: {report['timestamp']}")
    lines.append(f"- Wiki pages: {report['wiki_pages']}")
    lines.append(f"- Internal links OK: {report['internal_links_ok']}")
    lines.append(f"- Broken links: {len(report['broken_links'])}")
    lines.append(f"- Orphans: {len(report['orphans'])}")
    lines.append(f"- Stubs (<200 chars): {len(report['stubs'])}")
    lines.append(f"- Raw without wiki: {len(report['missing_raw'])}")
    lines.append(f"- Duplicate-ish stems: {len(report['dupes'])}")
    lines.append(f"- Quotes verity issues: {len(report['quotes_verity'])}")
    lines.append("")
    if report["broken_links"]:
        lines.append("## Broken links")
        for p, l, why in report["broken_links"]:
            lines.append(f"- `{p}` → `{l}` ({why})")
        lines.append("")
    if report["orphans"]:
        lines.append("## Orphans (no inbound links)")
        for o in report["orphans"]:
            lines.append(f"- {o}")
        lines.append("")
    if report["stubs"]:
        lines.append("## Stubs")
        for s, n in report["stubs"]:
            lines.append(f"- {s} ({n} chars)")
        lines.append("")
    if report["missing_raw"]:
        lines.append("## Raw without wiki")
        for m in report["missing_raw"]:
            lines.append(f"- {m}")
        lines.append("")
    if report["dupes"]:
        lines.append("## Duplicate-ish stems")
        for a, b in report["dupes"]:
            lines.append(f"- {a} ↔ {b}")
        lines.append("")
    if report["quotes_verity"]:
        lines.append("## Quotes verity (no-source | not-in-raw)")
        for p, q, kind in report["quotes_verity"]:
            lines.append(f"- `{p}` [{kind}]: {q}…")
        lines.append("")
    # Trend history (this run appended as the latest row)
    history = parse_history()
    history.append({
        "date": today,
        "pages": report["wiki_pages"],
        "links": report["internal_links_ok"],
        "broken": len(report["broken_links"]),
        "orphans": len(report["orphans"]),
        "stubs": len(report["stubs"]),
        "missing": len(report["missing_raw"]),
        "dupes": len(report["dupes"]),
        "quotes": len(report["quotes_verity"]),
    })
    lines.append("## Trend across runs")
    lines.append("")
    lines.extend(trend_lines(history))
    lines.append("")
    lines.append("Delta columns relative to previous run. First run has no deltas.")
    lines.append("")
    dst.write_text("\n".join(lines), encoding="utf-8")
    return dst


def exit_code(report: dict) -> int:
    if report["broken_links"]:
        return 1
    hard_quote_hits = [x for x in report["quotes_verity"] if x[2] == "not-in-raw"]
    if report["orphans"] or report["stubs"] or report["missing_raw"] or hard_quote_hits:
        return 2
    return 3 if (report["dupes"] or report["quotes_verity"]) else 0


def main():
    args = sys.argv[1:]
    is_summary = "--summary" in args
    is_json = "--json" in args

    report = run_all(verbose=not is_summary)

    if is_json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
        return
    dst = write_report(report)
    print(f"\n📝 Report: {dst}")
    print(f"👋 Exit code: {exit_code(report)}")
    sys.exit(exit_code(report))


if __name__ == "__main__":
    main()