#!/usr/bin/env python3
"""
wiki_lint.py — Deterministic health check for the AI QA Wiki (replaces manual Sunday ritual).

Checks (all deterministic, no LLM context):
  1. Broken internal links in wiki/ (links to wiki/*.md and raw/*.md that don't exist)
  2. Orphan pages (wiki/*.md with no inbound links from any other wiki page)
  3. Stub pages (<200 chars of content, excluding frontmatter/footers)
  4. Raw files without a wiki counterpart (uses wiki_llm.missing_raw_files)
  5. Duplicate titles (near-identical stems that may be dupes)

Usage:
    python3 wiki_lint.py                      — run ALL checks, print summary
    python3 wiki_lint.py --summary            — only counts, no per-page detail
    python3 wiki_lint.py --auto               — non-interactive, exit code 0 if no P1 broken links
    python3 wiki_lint.py --report-only        — just notes, don't fix
    python3 wiki_lint.py --fix-orphans        — create See-also cross-links from topically-related pages
    python3 wiki_lint.py --json               — machine-readable output

Exit codes:
    0 clean / nothing to fix
    1 P1 issues found (broken internal links)
    2 P2 issues found (orphans / stubs / missing)
    3 P3 only (informational)

Output: outputs/lint-report-YYYY-MM-DD.md (always written).
"""

import re
import sys
import json
import datetime
from pathlib import Path

PROJECT_DIR = Path(__file__).parent
WIKI_DIR = PROJECT_DIR / "wiki"
RAW_DIR = PROJECT_DIR / "raw"
OUTPUTS_DIR = PROJECT_DIR / "outputs"
REPORT_DIR = OUTPUTS_DIR

INTERNAL_LINK_RE = re.compile(r"\[[^\]]*\]\(((?:wiki|raw)/[^)#]+)\.md(?:#[\w-]+)?\)")
SKIP_FILES = {"log.md", "README.md", "index.md"}


def read_page(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""


def strip_boilerplate(content: str) -> str:
    """Remove frontmatter, backlinks block, and generated-footer to measure real content size."""
    lines = content.split("\n")
    out = []
    in_fm = False
    if lines and lines[0].strip() == "---":
        in_fm = True
    for ln in lines:
        if in_fm:
            if ln.strip() == "---":
                in_fm = False
            continue
        if "<!-- backlinks-start -->" in ln or "<!-- backlinks-end -->" in ln:
            continue
        if ln.startswith("*Generated by"):
            continue
        out.append(ln)
    return "\n".join(out)


def internal_links(content: str) -> list:
    return [m.group(1) + ".md" for m in INTERNAL_LINK_RE.finditer(content)]


def all_wiki_pages() -> list:
    return sorted(p for p in WIKI_DIR.glob("*.md") if p.name not in SKIP_FILES)


def check_broken_links() -> (list, list):
    """Returns (broken, ok_count). A link to wiki/x.md or raw/x.md is broken if file missing."""
    existing_wiki = {p.name for p in WIKI_DIR.glob("*.md")}
    existing_raw = {p.name for p in RAW_DIR.iterdir() if p.is_file()}
    broken = []
    ok = 0
    for p in all_wiki_pages():
        for link in internal_links(read_page(p)):
            if link.startswith("wiki/"):
                target = link[len("wiki/"):]
                if target not in existing_wiki:
                    broken.append((p.name, link, "wiki target missing"))
            elif link.startswith("raw/"):
                target = link[len("raw/"):]
                if target not in existing_raw:
                    broken.append((p.name, link, "raw target missing"))
            else:
                ok += 1
    return broken, ok


def inbound_links() -> dict:
    """Map every wiki page stem → set of stems that link to it."""
    incoming = {}
    pages = all_wiki_pages()
    for p in pages:
        content = read_page(p)
        for link in internal_links(content):
            if link.startswith("wiki/"):
                target = link[len("wiki/"):-3]
                incoming.setdefault(target, set()).add(p.stem)
    return incoming


def check_orphans() -> list:
    pages = all_wiki_pages()
    incoming = inbound_links()
    orphans = []
    for p in pages:
        if p.stem not in incoming:
            orphans.append(p.name)
    return orphans


def check_stubs(min_chars: int = 200) -> list:
    stubs = []
    for p in all_wiki_pages():
        size = len(strip_boilerplate(read_page(p)).strip())
        if size < min_chars:
            stubs.append((p.name, size))
    return stubs


def check_missing_raw() -> list:
    sys.path.insert(0, str(PROJECT_DIR))
    try:
        from wiki_llm import missing_raw_files
        return [f.name for f in missing_raw_files()]
    except Exception:
        return ["(wiki_llm import failed)"]


def check_dupes() -> list:
    """Near-identical stems that likely duplicate a topic."""
    pages = all_wiki_pages()
    stems = [p.stem for p in pages]
    dupes = []
    seen = {}
    for i, s in enumerate(stems):
        norm = re.sub(r"[^a-z0-9]", "", s.lower())
        if norm in seen:
            dupes.append((seen[norm], s))
        else:
            seen[norm] = s
    return dupes


def run_all(verbose: bool = True) -> dict:
    broken, ok_links = check_broken_links()
    orphans = check_orphans()
    stubs = check_stubs()
    missing = check_missing_raw()
    dupes = check_dupes()

    report = {
        "timestamp": datetime.datetime.now().isoformat(),
        "wiki_pages": len(all_wiki_pages()),
        "internal_links_ok": ok_links,
        "broken_links": broken,
        "orphans": orphans,
        "stubs": stubs,
        "missing_raw": missing,
        "dupes": dupes,
    }
    if verbose:
        print(f"\n🔍 Wiki lint ({report['wiki_pages']} pages)")
        print(f"  ✅ Internal links OK: {ok_links}")
        print(f"  ❌ Broken links: {len(broken)}")
        for p, l, why in broken:
            print(f"      {p} → {l} ({why})")
        print(f"  🕳️  Orphans: {len(orphans)}")
        for o in orphans[:40]:
            print(f"      {o}")
        if len(orphans) > 40:
            print(f"      … and {len(orphans)-40} more")
        print(f"  📄 Stubs (<200 chars): {len(stubs)}")
        for s, n in stubs[:40]:
            print(f"      {s} ({n} chars)")
        if len(stubs) > 40:
            print(f"      … and {len(stubs)-40} more")
        print(f"  ⚠️  Raw without wiki: {len(missing)}")
        for m in missing[:30]:
            print(f"      {m}")
        if len(missing) > 30:
            print(f"      … and {len(missing)-30} more")
        print(f"  🔁 Duplicate-ish stems: {len(dupes)}")
        for a, b in dupes[:30]:
            print(f"      {a} ↔ {b}")
    return report


def write_report(report: dict) -> Path:
    OUTPUTS_DIR.mkdir(exist_ok=True)
    today = datetime.date.today().isoformat()
    dst = REPORT_DIR / f"lint-report-{today}.md"
    lines = [f"# Wiki Lint Report — {today}", ""]
    lines.append(f"- Timestamp: {report['timestamp']}")
    lines.append(f"- Wiki pages: {report['wiki_pages']}")
    lines.append(f"- Internal links OK: {report['internal_links_ok']}")
    lines.append(f"- Broken links: {len(report['broken_links'])}")
    lines.append(f"- Orphans: {len(report['orphans'])}")
    lines.append(f"- Stubs (<200 chars): {len(report['stubs'])}")
    lines.append(f"- Raw without wiki: {len(report['missing_raw'])}")
    lines.append(f"- Duplicate-ish stems: {len(report['dupes'])}")
    lines.append("")
    if report["broken_links"]:
        lines.append("## Broken links")
        for p, l, why in report["broken_links"]:
            lines.append(f"- `{p}` → `{l}` ({why})")
        lines.append("")
    if report["orphans"]:
        lines.append("## Orphans (no inbound links)")
        for o in report["orphans"]:
            lines.append(f"- {o}")
        lines.append("")
    if report["stubs"]:
        lines.append("## Stubs")
        for s, n in report["stubs"]:
            lines.append(f"- {s} ({n} chars)")
        lines.append("")
    if report["missing_raw"]:
        lines.append("## Raw without wiki")
        for m in report["missing_raw"]:
            lines.append(f"- {m}")
        lines.append("")
    if report["dupes"]:
        lines.append("## Duplicate-ish stems")
        for a, b in report["dupes"]:
            lines.append(f"- {a} ↔ {b}")
        lines.append("")
    dst.write_text("\n".join(lines), encoding="utf-8")
    return dst


def exit_code(report: dict) -> int:
    if report["broken_links"]:
        return 1
    if report["orphans"] or report["stubs"] or report["missing_raw"]:
        return 2
    return 3 if report["dupes"] else 0


def main():
    args = sys.argv[1:]
    is_summary = "--summary" in args
    is_json = "--json" in args

    report = run_all(verbose=not is_summary)

    if is_json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
        return
    dst = write_report(report)
    print(f"\n📝 Report: {dst}")
    print(f"👋 Exit code: {exit_code(report)}")
    sys.exit(exit_code(report))


if __name__ == "__main__":
    main()